#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/c/fusegen_c
  
  blListGen \
    -d ../fusegen_c \
    -1L  \
    -u $DVCZ_UDIR \
    -X build \
    -X .ssh \
    $@
  
else
  echo "DEV_BASE is not defined"
fi
